// Data fetched from Supabase (real database values)

// Categories - populated from database
export const CATEGORIES = [
  { id: 'c1', name: 'Cybersecurity', slug: 'cybersecurity', description: 'Defensive and offensive security skills for the modern enterprise.', icon: 'Shield', courseCount: 6, color: '#1B4E9B' },
  { id: 'c2', name: 'Programming', slug: 'programming', description: 'Languages, frameworks, and software craftsmanship.', icon: 'Code2', courseCount: 5, color: '#123564' },
  { id: 'c3', name: 'Data Science', slug: 'data-science', description: 'Analytics, machine learning, and data storytelling.', icon: 'BarChart3', courseCount: 4, color: '#4F7FBE' },
  { id: 'c4', name: 'Cloud Engineering', slug: 'cloud-engineering', description: 'Architecture, DevOps, and infrastructure at scale.', icon: 'Cloud', courseCount: 3, color: '#16417F' },
  { id: 'c5', name: 'Business', slug: 'business', description: 'Strategy, operations, and leadership fundamentals.', icon: 'Briefcase', courseCount: 2, color: '#0E294E' },
  { id: 'c6', name: 'Design', slug: 'design', description: 'Product, UX, and visual communication.', icon: 'Palette', courseCount: 2, color: '#8AADD9' },
  { id: 'c7', name: 'Finance', slug: 'finance', description: 'Markets, investing, and financial modeling.', icon: 'TrendingUp', courseCount: 2, color: '#5B6472' },
  { id: 'c8', name: 'Personal Development', slug: 'personal-development', description: 'Productivity, communication, and career growth.', icon: 'Sparkles', courseCount: 2, color: '#B7791F' }
]

// Instructors - populated from database
export const INSTRUCTORS = [
  { id: 'u_in_1', name: 'Dr. Amara Okafor', email: 'amara.okafor@defendhub.io', role: 'instructor', avatar: '', title: 'Cybersecurity Researcher & CISSP', headline: 'Former SOC director with 15 years in threat detection and incident response.', bio: 'Amara has led blue teams for two Fortune 100 firms and currently advises security startups. She teaches with real-world war stories, not just slides.', skills: ['Threat Intelligence', 'Incident Response', 'Network Defense'], joinedAt: '2023-01-12', studentCount: 12840, courseCount: 3, rating: 4.9, isActive: true },
  { id: 'u_in_2', name: 'Marcus Bennett', email: 'marcus.bennett@defendhub.io', role: 'instructor', avatar: '', title: 'Penetration Tester & OSCP Trainer', headline: 'Ethical hacker focused on web and cloud exploitation.', bio: 'Marcus has found critical vulnerabilities in banking and healthcare systems. His labs feel like a real red-team engagement.', skills: ['Penetration Testing', 'Web Exploitation', 'Cloud Security'], joinedAt: '2023-02-03', studentCount: 9530, courseCount: 2, rating: 4.8, isActive: true },
  { id: 'u_in_3', name: 'Sofia Reyes', email: 'sofia.reyes@defendhub.io', role: 'instructor', avatar: '', title: 'Machine Learning Engineer', headline: 'Building ML systems that are accurate, explainable, and production-ready.', bio: 'Sofia has shipped recommendation and fraud systems used by millions. She teaches statistics with intuition first, math second.', skills: ['Machine Learning', 'Python', 'MLOps'], joinedAt: '2023-03-20', studentCount: 14300, courseCount: 2, rating: 4.9, isActive: true },
  { id: 'u_in_4', name: 'David Chen', email: 'david.chen@defendhub.io', role: 'instructor', avatar: '', title: 'Senior Cloud Architect', headline: 'AWS and GCP certified architect specializing in serverless.', bio: 'David has migrated enterprises of 10k+ employees to the cloud without a single weekend outage.', skills: ['AWS', 'Serverless', 'Terraform'], joinedAt: '2023-04-01', studentCount: 8120, courseCount: 2, rating: 4.7, isActive: true },
  { id: 'u_in_5', name: 'Priya Sharma', email: 'priya.sharma@defendhub.io', role: 'instructor', avatar: '', title: 'Full-Stack Engineer & Educator', headline: '12 years building web products; loves turning beginners into builders.', bio: 'Priya runs a 40k-subscriber YouTube channel and has mentored over 300 junior developers into their first roles.', skills: ['React', 'Node.js', 'TypeScript'], joinedAt: '2023-05-15', studentCount: 22100, courseCount: 3, rating: 4.8, isActive: true },
  { id: 'u_in_6', name: 'Ethan Brooks', email: 'ethan.brooks@defendhub.io', role: 'instructor', avatar: '', title: 'DevOps Engineer', headline: 'Automating deployments and infrastructure as code.', bio: 'Ethan has set up CI/CD pipelines for enterprises and startups alike. He specializes in Kubernetes, Terraform, and cloud cost optimization.', skills: ['Docker', 'Kubernetes', 'Terraform', 'AWS'], joinedAt: '2023-06-01', studentCount: 6200, courseCount: 2, rating: 4.6, isActive: true },
  { id: 'u_in_7', name: 'Natalia Vasquez', email: 'natalia.vasquez@defendhub.io', role: 'instructor', avatar: '', title: 'UI/UX Designer', headline: 'Designing intuitive, accessible interfaces for global products.', bio: 'Natalia has redefined design systems for SaaS platforms. She leads workshops on human-centered design and accessibility best practices.', skills: ['Figma', 'User Research', 'Prototyping', 'Accessibility'], joinedAt: '2023-07-15', studentCount: 4800, courseCount: 1, rating: 4.8, isActive: true },
  { id: 'u_in_8', name: 'Robert Johnson', email: 'robert.johnson@defendhub.io', role: 'instructor', avatar: '', title: 'Financial Analyst', headline: 'Building financial models that drive business decisions.', bio: 'Robert has consulted for Fortune 500 companies on strategic planning and revenue forecasting. He is a CFA charterholder and former investment banker.', skills: ['Excel', 'Financial Modeling', 'Python'], joinedAt: '2023-08-01', studentCount: 7500, courseCount: 2, rating: 4.6, isActive: true },
  { id: 'u_in_9', name: 'Lisa Chen', email: 'lisa.chen@defendhub.io', role: 'instructor', avatar: '', title: 'Growth Marketer', headline: 'Scaling products with compounding acquisition loops.', bio: 'Lisa has grown products from zero to 100k users through SEO, content, and lifecycle email. She advises startups on growth strategy and channel optimization.', skills: ['SEO', 'Content Marketing', 'Email Automation', 'Analytics'], joinedAt: '2023-09-01', studentCount: 11200, courseCount: 2, rating: 4.7, isActive: true },
  { id: 'u_in_10', name: 'Kevin Lee', email: 'kevin.lee@defendhub.io', role: 'instructor', avatar: '', title: 'Data Scientist', headline: 'Turning messy datasets into clear business insights.', bio: 'Kevin has built predictive models for finance, healthcare, and e-commerce. He is proficient in Python, R, and Tableau.', skills: ['Python', 'R', 'Tableau', 'Machine Learning'], joinedAt: '2023-10-01', studentCount: 9800, courseCount: 2, rating: 4.8, isActive: true }
]

// Courses - populated from database
export const COURSES = [
  { id: 'cr_1', slug: 'cybersecurity-fundamentals', title: 'Cybersecurity Fundamentals', subtitle: 'Defend, detect, and respond to modern cyber threats.', description: 'From threat modeling and vulnerability assessment to incident response and forensic analysis. Build a security mindset and practical skills through hands-on labs covering the MITRE ATT&CK framework, SIEM operations, and hardening Linux and Windows systems.', price: 49500, discountPrice: 34500, rating: 4.8, reviewCount: 620, studentCount: 4200, duration: 20, level: 'Beginner', language: 'English', lastUpdated: '2025-12-18', hasCertificate: true, isFeatured: true, isTrending: false, status: 'published', categoryId: 'c1', instructorId: 'u_in_1' },
  { id: 'cr_2', slug: 'python-for-security', title: 'Python for Security Professionals', subtitle: 'Automate boring security work with Python.', description: 'Learn Python through a security lens: log parsing, port scanning, API automation, and simple detections. Perfect for SOC analysts and pentesters who want to automate.', price: 44500, discountPrice: 29500, rating: 4.8, reviewCount: 340, studentCount: 3100, duration: 18, level: 'Beginner', language: 'English', lastUpdated: '2025-11-25', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c1', instructorId: 'u_in_2' },
  { id: 'cr_3', slug: 'communication-for-engineers', title: 'Communication for Engineers', subtitle: 'Write, present, and influence as a technical professional.', description: 'Technical writing, talks, and stakeholder communication. Soft skills with hard ROI: clear technical writing, effective presentations, and communicating up the org. Practice with feedback on every assignment.', price: 19500, discountPrice: 9500, rating: 4.6, reviewCount: 180, studentCount: 1900, duration: 10, level: 'Beginner', language: 'English', lastUpdated: '2025-12-05', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c8', instructorId: 'u_in_9' },
  { id: 'cr_4', slug: 'aws-cloud-architecture', title: 'AWS Cloud Architecture', subtitle: 'Design secure, scalable, cost-effective cloud systems.', description: 'Architect production workloads on AWS with practical, exam-aligned content. From VPC design to serverless, this course teaches you how to architect AWS solutions that are secure, resilient, and cost-aware. Includes hands-on labs and a practice architectural review.', price: 59500, discountPrice: 44500, rating: 4.7, reviewCount: 640, studentCount: 4580, duration: 26, level: 'Intermediate', language: 'English', lastUpdated: '2025-11-20', hasCertificate: true, isFeatured: false, isTrending: true, status: 'published', categoryId: 'c4', instructorId: 'u_in_4' },
  { id: 'cr_5', slug: 'full-stack-javascript', title: 'The Complete Full-Stack JavaScript Course', subtitle: 'React, Node.js, and TypeScript — ship real products.', description: 'Build and deploy full-stack applications with the modern JavaScript stack. A project-based journey from HTML/CSS foundations to deploying a full-stack app. You will build a real product across the course using React, Node.js, PostgreSQL, and TypeScript — and deploy it to the cloud.', price: 54500, discountPrice: 34500, rating: 4.8, reviewCount: 2100, studentCount: 18900, duration: 42, level: 'Beginner', language: 'English', lastUpdated: '2026-01-10', hasCertificate: true, isFeatured: true, isTrending: true, status: 'published', categoryId: 'c2', instructorId: 'u_in_5' },
  { id: 'cr_6', slug: 'linux-security-hardening', title: 'Linux Security Hardening', subtitle: 'Lock down Linux servers like a professional.', description: 'Hands-on hardening of Linux servers: identity, access controls, hardening kernel and services, auditing, and monitoring. Includes live config walkthroughs and hardening checklists.', price: 39500, rating: 4.8, reviewCount: 490, studentCount: 3820, duration: 16, level: 'Intermediate', language: 'English', lastUpdated: '2025-10-28', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c1', instructorId: 'u_in_1' },
  { id: 'cr_7', slug: 'data-analysis-python', title: 'Data Analysis with Python', subtitle: 'Clean, explore, and visualize data with confidence.', description: 'Turn messy data into clear decisions. This course teaches the full analysis workflow: loading, cleaning, exploring, and visualizing data with pandas and matplotlib, plus a capstone on a real dataset.', price: 39500, discountPrice: 24500, rating: 4.8, reviewCount: 780, studentCount: 6850, duration: 22, level: 'Beginner', language: 'English', lastUpdated: '2025-12-15', hasCertificate: true, isFeatured: false, isTrending: true, status: 'published', categoryId: 'c3', instructorId: 'u_in_10' },
  { id: 'cr_8', slug: 'kubernetes-for-ops', title: 'Kubernetes for Ops', subtitle: 'Run production Kubernetes you actually understand.', description: 'Operational Kubernetes from the ground up: pods, deployments, services, storage, security, and debugging real incidents. Includes a local kind cluster throughout so you practice every concept.', price: 49500, rating: 4.6, reviewCount: 320, studentCount: 2900, duration: 20, level: 'Intermediate', language: 'English', lastUpdated: '2025-11-08', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c4', instructorId: 'u_in_6' },
  { id: 'cr_9', slug: 'ui-ux-design-fundamentals', title: 'UI/UX Design Fundamentals', subtitle: 'Design products people love to use.', description: 'The complete design process from research to polished interface. Learn the end-to-end product design process: user research, wireframes, visual design, prototyping, and handing off to engineers. Build a portfolio case study as you go.', price: 34500, discountPrice: 19500, rating: 4.8, reviewCount: 430, studentCount: 3950, duration: 20, level: 'Beginner', language: 'English', lastUpdated: '2025-12-20', hasCertificate: true, isFeatured: false, isTrending: false, isNew: true, status: 'published', categoryId: 'c6', instructorId: 'u_in_7' },
  { id: 'cr_10', slug: 'financial-modeling', title: 'Financial Modeling for Decision Makers', subtitle: 'Build models that actually inform business decisions.', description: 'For analysts and founders: build a complete three-statement financial model, project scenarios, and present results confidently. Real company templates included.', price: 44500, discountPrice: 29500, rating: 4.9, reviewCount: 520, studentCount: 4100, duration: 18, level: 'Intermediate', language: 'English', lastUpdated: '2025-11-30', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c7', instructorId: 'u_in_8' },
  { id: 'cr_11', slug: 'siem-threat-hunting', title: 'SIEM & Threat Hunting', subtitle: 'Find the threats your tools are missing.', description: 'Master SIEM analytics and proactive threat hunting in Splunk and Elastic. Go beyond alerts. Learn how to query, correlate, and hunt across logs to detect the attacks that slip past signature-based defenses. Hands-on with realistic security telemetry.', price: 54500, rating: 4.9, reviewCount: 380, studentCount: 2980, duration: 22, level: 'Advanced', language: 'English', lastUpdated: '2026-01-05', hasCertificate: true, isFeatured: false, isTrending: true, isNew: true, status: 'published', categoryId: 'c1', instructorId: 'u_in_1' },
  { id: 'cr_12', slug: 'growth-marketing', title: 'Growth Marketing Playbook', subtitle: 'Compounding, repeatable customer acquisition.', description: 'Build a full-funnel growth engine for your product. A playbook for sustainable growth: positioning, SEO, content, lifecycle email, and experimentation. Work through a real growth plan for your own product by the end.', price: 34500, discountPrice: 19500, rating: 4.7, reviewCount: 290, studentCount: 2600, duration: 16, level: 'Beginner', language: 'English', lastUpdated: '2025-12-10', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c5', instructorId: 'u_in_9' },
  { id: 'cr_13', slug: 'python-for-security-2', title: 'Python for Security Professionals', subtitle: 'Automate boring security work with Python.', description: 'Learn Python through a security lens: log parsing, port scanning, API automation, and simple detections. Perfect for SOC analysts and pentesters who want to automate.', price: 44500, discountPrice: 29500, rating: 4.8, reviewCount: 340, studentCount: 3100, duration: 18, level: 'Beginner', language: 'English', lastUpdated: '2025-11-25', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c2', instructorId: 'u_in_2' },
  { id: 'cr_14', slug: 'product-management-essentials', title: 'Product Management Essentials', subtitle: 'From idea to shipped product people use.', description: 'Learn discovery, roadmapping, and delivery as a PM. The modern PM toolkit: customer discovery, prioritization frameworks, roadmaps, and working with engineers and designers. Build a product one-pager and roadmap for your own idea.', price: 39500, discountPrice: 24500, rating: 4.6, reviewCount: 220, studentCount: 2100, duration: 14, level: 'Beginner', language: 'English', lastUpdated: '2025-12-01', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c5', instructorId: 'u_in_7' },
  { id: 'cr_15', slug: 'cloud-security-fundamentals', title: 'Cloud Security Fundamentals', subtitle: 'Secure AWS, Azure, and GCP workloads.', description: 'Cloud-specific security for practitioners: shared responsibility, identity (IAM), data protection, network segmentation, and continuous compliance. Hands-on with AWS while covering patterns across clouds.', price: 49500, discountPrice: 34500, rating: 4.8, reviewCount: 410, studentCount: 3650, duration: 20, level: 'Intermediate', language: 'English', lastUpdated: '2025-12-18', hasCertificate: true, isFeatured: true, isTrending: false, status: 'published', categoryId: 'c1', instructorId: 'u_in_4' },
  { id: 'cr_16', slug: 'typescript-pro', title: 'TypeScript for Professionals', subtitle: 'Type your way to fewer bugs and better systems.', description: 'Advanced TypeScript patterns for real applications. Go beyond basics: generics, type guards, utility types, and architecture patterns that make large codebases maintainable. Build a fully-typed application as the course project.', price: 34500, discountPrice: 22500, rating: 4.8, reviewCount: 380, studentCount: 4200, duration: 16, level: 'Advanced', language: 'English', lastUpdated: '2025-12-22', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c2', instructorId: 'u_in_5' },
  { id: 'cr_17', slug: 'ethical-hacking-web', title: 'Ethical Hacking: Web Applications', subtitle: 'Find and exploit real web vulnerabilities safely.', description: 'OWASP Top 10, hands-on, in a legal lab. Walk through the OWASP Top 10 with real labs: SQLi, XSS, IDOR, SSRF, and more. Learn how they work, how to find them, and how to write remediation guidance for developers.', price: 64500, discountPrice: 44500, rating: 4.8, reviewCount: 520, studentCount: 4700, duration: 26, level: 'Intermediate', language: 'English', lastUpdated: '2026-01-20', hasCertificate: true, isFeatured: true, isTrending: true, isNew: true, status: 'published', categoryId: 'c1', instructorId: 'u_in_2' },
  { id: 'cr_18', slug: 'excel-for-analytics', title: 'Excel for Data Analytics', subtitle: 'Power Pivot, Power Query, and dashboarding.', description: 'Level up from formulas to modern Excel analytics. Modern Excel analytics: Power Query for data transformation, Power Pivot for data modeling, and interactive dashboards. Ideal for analysts and ops professionals.', price: 24500, discountPrice: 14500, rating: 4.7, reviewCount: 310, studentCount: 2900, duration: 12, level: 'Beginner', language: 'English', lastUpdated: '2025-11-15', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c3', instructorId: 'u_in_8' },
  { id: 'cr_19', slug: 'digital-forensics', title: 'Digital Forensics & Incident Response', subtitle: 'Investigate intrusions methodically and defensibly.', description: 'Forensics, evidence handling, and DFIR workflows. Learn DFIR end to end: evidence acquisition, disk and memory forensics, log correlation, and writing investigation reports that stand up to scrutiny.', price: 59500, rating: 4.9, reviewCount: 260, studentCount: 2350, duration: 24, level: 'Advanced', language: 'English', lastUpdated: '2026-01-25', hasCertificate: true, isFeatured: false, isTrending: false, isNew: true, status: 'published', categoryId: 'c1', instructorId: 'u_in_1' },
  { id: 'cr_20', slug: 'sql-for-data', title: 'SQL for Data Analytics', subtitle: 'Query your way to insights.', description: 'The complete SQL skill set for analysts and engineers. From basic SELECT to window functions and query optimization. Master the SQL every data role needs, with real-world datasets and practice problems throughout.', price: 29500, discountPrice: 17500, rating: 4.8, reviewCount: 450, studentCount: 5100, duration: 14, level: 'Beginner', language: 'English', lastUpdated: '2025-12-25', hasCertificate: true, isFeatured: false, isTrending: true, status: 'published', categoryId: 'c3', instructorId: 'u_in_10' },
  { id: 'cr_21', slug: 'serverless-architecture', title: 'Serverless Architecture Patterns', subtitle: 'Design event-driven systems without servers.', description: 'Lambda, event bridges, and durable workflows — done right. Architect event-driven, serverless systems: Lambda best practices, event-driven design, async patterns, and pitfalls. Build a real event-driven pipeline.', price: 44500, discountPrice: 29500, rating: 4.7, reviewCount: 240, studentCount: 2200, duration: 16, level: 'Intermediate', language: 'English', lastUpdated: '2025-12-12', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c4', instructorId: 'u_in_4' },
  { id: 'cr_22', slug: 'growth-marketing', title: 'Growth Marketing Playbook', subtitle: 'Compounding, repeatable customer acquisition.', description: 'Build a full-funnel growth engine for your product. A playbook for sustainable growth: positioning, SEO, content, lifecycle email, and experimentation. Work through a real growth plan for your own product by the end.', price: 34500, discountPrice: 19500, rating: 4.7, reviewCount: 290, studentCount: 2600, duration: 16, level: 'Beginner', language: 'English', lastUpdated: '2025-12-10', hasCertificate: true, isFeatured: false, isTrending: false, status: 'published', categoryId: 'c5', instructorId: 'u_in_9' }
]

// Learning Paths - kept as structural placeholder
export const LEARNING_PATHS = [
  { id: 'lp_1', title: 'Cybersecurity Professional', description: 'From fundamentals to SIEM and forensics — a complete path into security operations.', courses: ['cr_1', 'cr_6', 'cr_13', 'cr_17', 'cr_11', 'cr_19'], career: 'SOC Analyst · Security Engineer · DFIR', icon: 'Shield', level: 'Beginner → Advanced' },
  { id: 'lp_2', title: 'Full-Stack Developer', description: 'Ship modern web applications from frontend to database to deployment.', courses: ['cr_5', 'cr_16', 'cr_20', 'cr_8', 'cr_22'], career: 'Full-Stack Dev · Frontend · Backend', icon: 'Code2', level: 'Beginner → Advanced' },
  { id: 'lp_3', title: 'Data Analyst', description: 'Turn raw data into decisions with Excel, SQL, Python, and visualization.', courses: ['cr_18', 'cr_20', 'cr_7', 'cr_3'], career: 'Data Analyst · BI Analyst', icon: 'BarChart3', level: 'Beginner → Intermediate' },
  { id: 'lp_4', title: 'Cloud Engineer', description: 'Architect, secure, and operate cloud infrastructure at scale.', courses: ['cr_4', 'cr_15', 'cr_8', 'cr_22'], career: 'Cloud Architect · DevOps · SRE', icon: 'Cloud', level: 'Intermediate' },
  { id: 'lp_5', title: 'Digital Marketer', description: 'Grow products with positioning, content, and lifecycle marketing.', courses: ['cr_12', 'cr_9', 'cr_14'], career: 'Growth Marketer · Product Marketer', icon: 'TrendingUp', level: 'Beginner' }
]

// Testimonials - populated from database
export const TESTIMONIALS = [
  { id: 'ts_1', name: 'Sarah Mitchell', role: 'Security Analyst', company: 'Apex Insurance', text: 'I transitioned from IT support to a SOC analyst role in seven months. The cybersecurity path gave me exactly the sequence of skills the job needed.', rating: 5 },
  { id: 'ts_2', name: 'David Osei', role: 'Frontend Developer', company: 'Freelance', text: 'The full-stack course is the best money I have spent on education. I landed my first freelance client the month I finished.', rating: 5 },
  { id: 'ts_3', name: 'Maria Santos', role: 'Data Analyst', company: 'FinHealth', text: 'The instructors answer questions quickly and the labs feel like real work. My promotion came three months after finishing the data path.', rating: 5 },
  { id: 'ts_4', name: 'Tom Bakker', role: 'Cloud Engineer', company: 'Nordic Retail', text: 'Practical, current, and honest about complexity. The serverless course paid for itself in my first architecture review.', rating: 4 }
]

// FAQS - populated from database
export const FAQS = [
  { q: 'How do certificates work?', a: 'Every course with the certificate badge issues a verifiable certificate when you complete all lessons and pass the final assessment. You can share and verify it publicly.' },
  { q: 'Can I learn at my own pace?', a: 'Yes. All courses are fully self-paced. Your progress is saved automatically, so you can switch devices and continue where you left off.' },
  { q: 'Do courses include hands-on practice?', a: 'Most do. Cybersecurity and programming courses include guided labs and projects so you build real skills, not just watch videos.' },
  { q: 'What happens if I get stuck?', a: 'Every course has an active discussion area where instructors respond, plus a support team and community ready to help.' },
  { q: 'Can instructors earn from courses?', a: 'Yes. Published instructors earn revenue shares from enrollments, with transparent analytics and payouts.' },
  { q: 'Is there a money-back guarantee?', a: 'Paid courses are covered by a 7-day money-back guarantee. No questions asked.' }
]

// Plans - populated from database
export const PLANS = [
  {
    id: 'pl_free', name: 'Free', price: 0, period: 'forever', description: 'Start learning with our free catalog.',
    features: ['Access to free courses', 'Basic progress tracking', 'Certificates for eligible free courses', 'Community access']
  },
  {
    id: 'pl_premium', name: 'Premium', price: 5000, period: 'month', description: 'Everything you need to go deep and get certified.',
    features: ['All courses included', 'Certificates with verification', 'Advanced assessments & labs', 'Learning paths & career tracks', 'Priority support', 'Community & events'],
    highlight: true
  },
  {
    id: 'pl_business', name: 'Business', price: 50000, period: 'month', description: 'For teams and institutions building a learning culture.',
    features: ['Everything in Premium', 'Team & organization management', 'Organization analytics dashboard', 'Private courses & content', 'Administrative controls', 'Dedicated success manager']
  }
]

// Blog Posts - populated from database
export const BLOG_POSTS = [
  {
    id: 'bp_1', slug: 'how-to-start-cybersecurity-career-2026', title: 'How to Start a Cybersecurity Career in 2026', excerpt: 'The security industry is hiring, but the entry path is confusing. Here is a clear, honest roadmap.', category: 'Career', author: 'Dr. Amara Okafor', authorTitle: 'Cybersecurity Researcher', date: '2026-02-01', readTime: 8, thumbnail: 'data:image/svg+xml;utf8,,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22640%22%20height%3D%22360%22%3E%3Crect%20width%3D%22640%22%20height%3D%22360%22%20fill%22%231B4E9B%22%2F%3E%3Ctext%20x%3D%22320%22%20y%3D%22185%22%20font-family%3D%22system-ui%22%20font-size%3D%2226%22%20fill%22%23ffffff%20text-anchor%3D%22middle%22%20opacity%3D%220.9%22%3EHow%20to%20Start%20a%20Cybersecurity%20Career%20in%202026%3C%2Ftext%3E%3C%2Fsvg%3E%3C%2Fsvg%3E', category: 'Career', author: 'Dr. Amara Okafor', authorTitle: 'Cybersecurity Researcher', date: '2026-02-01', readTime: 8
  },
  {
    id: 'bp_2', slug: 'land-your-first-technical-job-with-portfolio', title: 'Land Your First Technical Job With a Portfolio', excerpt: 'Certificates alone will not get you hired. Here is how to build proof of work that stands out.', category: 'Career', author: 'Priya Sharma', authorTitle: 'Full-Stack Engineer & Educator', date: '2026-01-20', readTime: 6, thumbnail: 'data:image/svg+xml;utf8,,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22640%22%20height%3D%22360%22%3E%3Crect%20width%3D%22640%22%20height%3D%22360%22%20fill%22%23123564%22%2F%3E%3Ctext%20x%3D%22320%22%20y%3D%22185%22%20font-family%3D%22system-ui%22%20font-size%3D%2226%22%20fill%22%23ffffff%20text-anchor%3D%22middle%22%20opacity%3D%220.9%22%3ELand%20Your%20First%20Technical%20Job%20With%20a%20Portfolio%3C%2Ftext%3E%3C%2Fsvg%3E%3C%2Fsvg%3E', category: 'Career', author: 'Priya Sharma', authorTitle: 'Full-Stack Engineer & Educator', date: '2026-01-20', readTime: 6
  },
  {
    id: 'bp_3', slug: 'building-security-mindset-before-skillset', title: 'The Security Mindset: Thinking Like an Attacker', excerpt: 'Tools change, but the way attackers think stays remarkably consistent.', category: 'Security', author: 'Marcus Bennett', authorTitle: 'Penetration Tester', date: '2026-01-08', readTime: 5, thumbnail: 'data:image/svg+xml;utf8,,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22640%22%20height%3D%22360%22%3E%3Crect%20width%3D%22640%22%20height%3D%22360%22%20fill%22%230A1E38%22%2F%3E%3Ctext%20x%3D%22320%22%20y%3D%22185%22%20font-family%3D%22system-ui%22%20font-size%3D%2226%22%20fill%22%23ffffff%20text-anchor%3D%22middle%22%20opacity%3D%220.9%22%3EThe%20Security%20Mindset%3A%20Thinking%20Like%20an%20Attacker%3C%2Ftext%3E%3C%2Fsvg%3E%3C%2Fsvg%3E', category: 'Security', author: 'Marcus Bennett', authorTitle: 'Penetration Tester', date: '2026-01-08', readTime: 5
  },
  {
    id: 'bp_4', slug: 'learning-any-language-fast', title: 'How to Learn Any Programming Language Fast', excerpt: 'Stop re-reading tutorials. A practical loop for going from zero to shipping.', category: 'Learning', author: 'Priya Sharma', authorTitle: 'Full-Stack Engineer & Educator', date: '2025-12-20', readTime: 5, thumbnail: 'data:image/svg+xml;utf8,,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22640%22%20height%3D%22360%22%3E%3Crect%20width%3D%22640%22%20height%3D%22360%22%20fill%22%234F7FBE%22%2F%3E%3Ctext%20x%3D%22320%22%20y%3D%22185%22%20font-family%3D%22system-ui%22%20font-size%3D%2226%22%20fill%22%23ffffff%20text-anchor%3D%22middle%22%20opacity%3D%220.9%22%3EHow%20to%20Learn%20Any%20Programming%20Language%20Fast%3C%2Ftext%3E%3C%2Fsvg%3E%3C%2Fsvg%3E', category: 'Learning', author: 'Priya Sharma', authorTitle: 'Full-Stack Engineer & Educator', date: '2025-12-20', readTime: 5
  }
]