export {
  initializeFirebaseAdmin,
  getFirebaseAdminAuth,
  getFirebaseAdminFirestore,
  getFirebaseAdminStorage,
  resetFirebaseAdmin,
} from "./admin";

// Re-export the getter functions with convenient names
export { getFirebaseAdminAuth as getAuth, getFirebaseAdminFirestore as getDb, getFirebaseAdminStorage as getStorage } from "./admin";

export {
  buildQuery,
  getDocuments,
  getDocument,
  getDocumentById,
  createDocument,
  updateDocument,
  deleteDocument,
  deleteDocumentById,
  getBatch,
  commitBatch,
  collectionRef,
  docRef,
  serverTimestamp,
  increment,
  arrayUnion,
  arrayRemove,
  deleteField,
  type QueryOptions,
  type FirestoreFilterOperator,
} from "./firestore";

export {
  collections,
  getCollection,
  type UserDoc,
  type MemberDoc,
  type ArticleDoc,
  type GalleryItemDoc,
  type PartnerDoc,
  type TeamMemberDoc,
  type ProductDoc,
  type FaqItemDoc,
  type CareerDoc,
  type DepartmentDoc,
  type ContactMessageDoc,
  type NewsletterSubscriptionDoc,
  type WaitlistDoc,
  type JobApplicationDoc,
  type ConversationDoc,
  type MessageDoc,
  type ConversationParticipantDoc,
  type CommentDoc,
  type LikeDoc,
  type MembershipPlanDoc,
  type PlanPricingDoc,
  type FeatureAccessDoc,
  type UserSubscriptionDoc,
  type PaymentDoc,
  type InvoiceDoc,
  type CourseDoc,
  type LessonDoc,
  type EnrollmentDoc,
  type QuizDoc,
  type QuizAttemptDoc,
  type CertificateDoc,
  type QuizQuestionDoc,
  type LessonProgressDoc,
  type AnalyticsEventDoc,
  type EmailTemplateDoc,
  type ActivityLogDoc,
  type SessionDoc,
} from "./collections";

export {
  createUser,
  getUserByUid,
  getUserByEmail,
  updateUser,
  deleteUser,
  verifyIdToken,
  verifyIdTokenAndCheckRevoked,
  createCustomToken,
  setCustomUserClaims,
  revokeRefreshTokens,
  listUsers,
  importUsers,
  getUserByPhoneNumber,
  getAuthInstance,
  type AuthUser,
} from "./auth";

export {
  uploadFile,
  uploadFileFromPath,
  deleteFile,
  getFileMetadata,
  getSignedUrl,
  getUploadSignedUrl,
  getDownloadSignedUrl,
  makeFilePublic,
  makeFilePrivate,
  copyFile,
  moveFile,
  listFiles,
  getBucket,
  getStorageInstance,
  DEFAULT_BUCKET,
  type UploadResult,
  type SignedUrlOptions,
} from "./storage";